### PR TITLE
Advanced Level

### PR DESCRIPTION
**Pull request by LayavardhanReddy024**
I have successfully completed the tasks on advanced level.
verify the codes and merge it.

### CODE REVIEW

**Comment by CSEdgeOff** [comment]
Add a Readme.md about your code Document it well and organized.

**Comment by LayavardhanReddy024** [comment]
i can't find a way to add readme file.

________________________________

**Comment by LayavardhanReddy024** [comment]
Greetings for the day
I have completed the advanced tasks in python programming internship but i
didn't get the Letter Of Recommendation (LOR) as you mentioned in the mail.

**Comment by CSEdgeOff** [comment]
Dear Intern,

Thank you for your interest in receiving a Letter of Recommendation (LOR)
from CSEdge. We appreciate your hard work and contributions during your
internship.

To ensure consistency and fairness in our recommendation process, we
typically send LORs to interns in a three-month cycle. This means there
might be a wait until the next cycle for your official LOR.

Team CSEdge

**Pull request merged**
